### ISSUE TITLE
Use CloudflareStreamApiClient::fromUrl() for async upload?

### ISSUE THREAD

**Issue by micschk** [restruct/silverstripe-cfstreamvideo#1]
Now it seems we're POST uploading vids to CF onBeforeWrite, this may probably delay the UI considerably(?)
Instead I propose:
- We move the handling (vid upload etc) to onAfterWrite (so we at least have a DB record to 'resume' or log any errors etc to first)
- We use the fromUrl method instead, as I think that would trigger CF to download the file (hopefully in the background, after first returning)
- In case of 'protected' or unpublished vid URLs we could think about a way to provide a one-time or secret link somehow?

**Comment by lekoala** [comment]
@micschk you are right, i moved the methods to onAfterWrite and used the fromUrl (fallback to regular upload if not working... since i'm testing locally, this is what happens, i should try on a live server)
for protected or unpublished urls, we can provide a link through our custom admin I provided both in the last commit
